authorization:
  service:
    jwt:
      secret: ${JWT_SECRET:placeholder}
    special:
      chars: "!,@,#,$,%,^,&,*,(,)"
spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect