spring:
  application:
    name: authorization
  profiles:
    active: dev, local
  config:
    import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh
